[deploy]
bucket = 'cfn-artifacts-cruddurmitchpuersten'
region = 'ca-central-1'
stack_name = 'CrdSyncRole'

[parameters]
GitHubOrg = 'MitchP95'
RepositoryName = 'AWS-Bootcamp-Cruddur'
OIDCProviderArn = ''