#! /usr/bin/env bash
set -e

FUNC_DIR="/workspace/AWS-Bootcamp-Cruddur/ddb/cruddur-messaging-stream"
TEMPLATE_PATH="/workspace/AWS-Bootcamp-Cruddur/ddb/template.yaml"
CONFIG_PATH="/workspace/AWS-Bootcamp-Cruddur/ddb/config.toml"

sam validate -t $TEMPLATE_PATH

echo "- build"
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html

sam build \
--use-container \
--config-file $CONFIG_PATH \
--template $TEMPLATE_PATH \
--base-dir $FUNC_DIR